name: Saturn
version: dev-SNAPSHOT
main: br.com.main.Saturn
author: Kinox
description: Plugin desenvolvido por Jhonata Augusto (Kinox)
commands:
  tag:
  setperm:
  removeperm:
  setvip:
  tempban:
  spec:
  quit:
  status:
  tell:
  build:
  ping:
  chat:
  duel:
  aceitar:
  recusar:
  partida:
  # Commands must be removed from Saturn
  pl:
  ver:
  about:
  me:
  nametagedit:
  ne:
  nte:
  viaversion:
  gamemode:
